### ISSUE TITLE
Mac 上安装失败

### ISSUE THREAD

**Issue by bestswifter** [xudafeng/app-inspector#3]
报错信息如下所示，希望得到解答：

➜  node_modules npm i app-inspector -g
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/Users/zxy/.nvm/versions/node/v6.2.2/bin/inspector -> /Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/bin/app-inspector
/Users/zxy/.nvm/versions/node/v6.2.2/bin/app-inspector -> /Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/bin/app-inspector

> fsevents@1.0.14 install /Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2016-08-07 21:24:34.896 xcodebuild[2070:8873364] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-08-07 21:24:34.902 xcodebuild[2070:8873364] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUFullIssueNavigator.xcplugin' not present in DVTPlugInCompatibilityUUIDs
objc[2070]: Class MCLog is implemented in both /Users/zxy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin/Contents/MacOS/MCLog and /Users/zxy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CodePilot3.xcplugin/Contents/MacOS/CodePilot3. One of the two will be used. Which one is undefined.
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> webdriveragent@1.0.16 install /Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/node_modules/webdriveragent
> unzip -o ./WebDriverAgent.zip -d ./ 1>/dev/null

> uiautomator-client@1.0.16 install /Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/node_modules/uiautomator-client
> node ./scripts/build.js

/Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:164
      throw e;
      ^

Error: $JAVA_HOME is not set
    at checkJavaHome.then.catch.then.then.catch.then.std (/Users/zxy/.nvm/versions/node/v6.2.2/lib/node_modules/app-inspector/node_modules/java-home/lib/java-home.js:89:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
/Users/zxy/.nvm/versions/node/v6.2.2/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/zxy/.nvm/versions/node/v6.2.2/bin/node" "/Users/zxy/.nvm/versions/node/v6.2.2/bin/npm" "i" "app-inspector" "-g"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! uiautomator-client@1.0.16 install: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uiautomator-client@1.0.16 install script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uiautomator-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uiautomator-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uiautomator-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zxy/node_modules/npm-debug.log
npm ERR! code 1

**Comment by xudafeng** [comment]
@bestswifter 请配置环境 http://macacajs.github.io/macaca/environment-setup.html
